services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_container:5432/mydatabase
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3000"

volumes:
  postgres_data:
